### ISSUE TITLE
Issue on parsing new symbol section.

### ISSUE THREAD

**Issue by ByunghunLee** [xR3b0rn/dbcppp#10]
Errors occur when new symbol section starts with "NS_  :" which comply with the vector DBC specification. However, it starts with "NS_:" in your test DBC file.

Errors occur when new symbols have a tab space.

```
NS_  :
	NS_DESC_
	CM_
	BA_DEF_
	BA_
	VAL_
	CAT_DEF_
	CAT_
	FILTER
	BA_DEF_DEF_
	EV_DATA_
	ENVVAR_DATA_
	SGTYPE_
	SGTYPE_VAL_
	BA_DEF_SGTYPE_
	BA_SGTYPE_
	SIG_TYPE_REF_
	VAL_TABLE_
	SIG_GROUP_
	SIG_VALTYPE_
	SIGTYPE_VALTYPE_
	BO_TX_BU_
	BA_DEF_REL_
	BA_REL_
	BA_DEF_DEF_REL_
	BU_SG_REL_
	BU_EV_REL_
	BU_BO_REL_
	SG_MUL_VAL_
```

**Comment by xR3b0rn** [comment]
What kind of errors? If there are no errors from the parser itself, everything is fine.
