### ISSUE TITLE
Why do signals have multiple multiplexer values?

### ISSUE THREAD

**Issue by bmcpt** [xR3b0rn/dbcppp#115]
Signals have a field `signal_multiplexer_values` which is a vector:
https://github.com/xR3b0rn/dbcppp/blob/067abf5609788b24626ab9b496aa96d4b5d252a5/src/libdbcppp/SignalImpl.h#L88

But when I open a DBC file in candb++, it only allows me to set a single multiplexer for each signal. What is the reason for making this field a vector?

**Comment by xR3b0rn** [comment]
In DBC it is possible to specify multiple layers of multiplexer values using the extended multiplexers. The DBC construct is called `SG_MUL_VAL_ `. You can find an example DBC [here](https://github.com/xR3b0rn/dbcppp/blob/master/tests/test_files/dbc/issue_184_extended_mux_independent_multiplexors_dumped.dbc).
