### ISSUE TITLE
Extern c API issue

### ISSUE THREAD

**Issue by ByunghunLee** [xR3b0rn/dbcppp#12]
The _dbcppp_NetworkGetVersion_ method returns a result of the getComment() method.

```cpp
const char* dbcppp_NetworkGetVersion(struct dbcppp_Network* net)
{
	const NetworkImpl* neti = reinterpret_cast<NetworkImpl*>(net);
	return neti->getComment().c_str();
}
```

**Comment by ByunghunLee** [comment]
Hello xR3b0rn,

I would like to commit a new feature. Would you allow me to commit it,
please?


2020년 3월 14일 (토) 오전 9:03, xR3b0rn <notifications@github.com>님이 작성:

**Comment by xR3b0rn** [comment]
feel free to create a pull request
