### ISSUE TITLE
C++ Markdown Example Update

### ISSUE THREAD

**Issue by jtf107** [xR3b0rn/dbcppp#14]
Looks like some of the function names and method of using the library has changed. Could you please update the C++ markdown to reflect those changes. For example rawToPhys vs raw_to_phys and decode. 

Also per the example I'm unable to create an network from dbc unless I've opened the dbc file first. 

I understand its not a build-able example but more documentation on how to decode a can_frame to individual signals and values would be appreciated.

**Comment by xR3b0rn** [comment]
> Also per the example I'm unable to create an network from dbc unless I've opened the dbc file first.
Sorry, but I do not understand the problem, can you clarify what you are intended in?

**Comment by xR3b0rn** [comment]
I closed this due to inactivity.
