### ISSUE TITLE
charconv: No such file or directory

### ISSUE THREAD

**Issue by wongtb** [xR3b0rn/dbcppp#23]
I am having an issue while running the "make -j" command. 

![image](https://user-images.githubusercontent.com/10664817/86164395-b37cdf00-badf-11ea-9ec4-a0197644c26d.png)

Doing some searching, <charconv> was a header introduced in 2017 libstdc++.  I am currently running Ubuntu 18.04LTS and have attempted to update libstdc++.  Pretty new to this work - any help is greatly appreciated.

**Comment by xR3b0rn** [comment]
Thanks for your reply.

What compiler version are you using?
If you are using g++:
```
sudo add-apt-repository ppa:ubuntu-toolchain-r/test
sudo apt-get update
sudo apt install gcc-10
```
Then configure dbcppp with:
```
cmake -DCMAKE_C_COMPILER=gcc-10 -DCMAKE_CXX_COMPILER=g++-10
```

**Comment by xR3b0rn** [comment]
I tunred out, that the <charconv>-header isn't needed anymore, so I removed it. You could try `git pull` and `make` again.

**Comment by wongtb** [comment]
Thank you so much for the quick reply and changes, you're awesome! I am much closer in making [96%], now with an issue <filesystem> being missing.  

I will spend some time to work out the compiler issues and the intricacies of CMake before re-posting.  

Thanks again!

**Comment by xR3b0rn** [comment]
Filesystem is indespensable, you have to update your compiler version. I don't know which version is the lowest possible but `g++-9` is defenetly working. Let me know if you make it run with a lower version.
