### ISSUE TITLE
can't revolse boost const

### ISSUE THREAD

**Issue by aaronduignan** [xR3b0rn/dbcppp#24]
Hey, I am having an issue with `make -j` with regards to boost

![boost_issue](https://user-images.githubusercontent.com/35932556/86460139-c0881100-bd1f-11ea-921f-596ab1fac4aa.png)

I think I haven't configured boost correctly. I haven't used it before and I wondering if you could help me?

**Comment by xR3b0rn** [comment]
Thanks for your post.
This error comes from an too old boost version. Update boost and it will compile.

**Comment by aaronduignan** [comment]
Thank you for your quick response. Yes I updated to 1.73 after I seen this issue https://github.com/xR3b0rn/dbcppp/issues/19

Builds now but seem to get a permissions issue installing it. 

![install_issue](https://user-images.githubusercontent.com/35932556/86467646-a8b78980-bd2d-11ea-93a7-adbf5ef6d716.png)

Any ideas what might be causing this? I tried `sudo` but that didn't work

**Comment by xR3b0rn** [comment]
Installation has to be done with root rights:
```
sudo make install
```
