### ISSUE TITLE
undefined reference to `dbcppp::Network::fromDBC(std::istream&)'

### ISSUE THREAD

**Issue by TheYonkk** [xR3b0rn/dbcppp#26]
I'd like to use this library for decoding  messages from a can socket, but I can't seem to get past just the simple example script.

First, I had some trouble using CMake and the g++ compiler. I'm using Ubuntu 16.04, so after reading some of the other issues, I updated to gcc 9 and CMake 17.03. Installation seems to hang up on a few weird spots (like trying to install using regex expressions for file name lists `*.h`), but I think I got it figured out.

I created a simple test script that attempted to only load in a DBC file, but got the error `undefined reference to 'dbcppp::Network::fromDBC(std::istream&)'`. I'm pretty sure it's something wrong with my installation, so I decided to try the BasicUsage example in the Examples directory. I figured that it references the .h files in the local repository, so that should rule out installation errors. However, the same issue arises. The command that I'm using to compile is `g++ --std=c++17 main.cpp`, so nothing special there.

I'm not too experienced with cpp, but is it possible only use the DBC loading and message decoding features of the library without compiling the command line tools?

**Comment by xR3b0rn** [comment]
Thanks for your report,, I was able to reconstruct the error. I will fix this as sonn as possible, you can expect tomorrow.

**Comment by xR3b0rn** [comment]
I fixed a bug in the `CMakeLists.txt`.
I am not sure if the tests are still wroking, so after you have applied my changes on your local installation, you can try to execute the following test progam:
```C++
// main.cpp
#include <fstream>
#include <iostream>
#include <dbcppp/Network.h>
#include <dbcppp/Network2Functions.h>
int main(int argc, char** args)
{
        std::ifstream is(args[1]);
        auto net = dbcppp::Network::fromDBC(is);
        using namespace dbcppp::Network2Human;
        std::cout << *net;
}
```
Compile it with:
```
g++ main.cpp -ldbcppp
```
And execute:
```
./a.out "path/to/dbc"
```

**Comment by TheYonkk** [comment]
Works like a charm! Thank you so much!
