### ISSUE TITLE
Cmake stripping RPATH when installing, libxmlmm.so not found

### ISSUE THREAD

**Issue by derkomai** [xR3b0rn/dbcppp#31]
When installing to sytem, libdbcppp.so rpath is stripped so it can't find and load libxmlmm.so despite being next to it.

```
-- Installing: /usr/local/lib/libdbcppp.so
-- Set runtime path of "/usr/local/lib/libdbcppp.so" to ""
```

The result of ` ldd /usr/local/lib/libdbcppp.so` is:
```
	linux-vdso.so.1 (0x00007f2079e47000)
	libxmlmm.so => not found          <-------------------------- There's the problem
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f20786f1000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f20784d9000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f20780e8000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f2077d4a000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f2079c1f000)
```

I've tried with `set_property(TARGET dbcppp PROPERTY INSTALL_RPATH_USE_LINK_PATH TRUE)` without luck for now. Any ideas?

**Comment by xR3b0rn** [comment]
Can you try to add `set(CMAKE_INSTALL_RPATH_USE_LINK_PATH true)` to the CMakeLists.txt in the root directory and then reconfigure and reinstall?

**Comment by derkomai** [comment]
I did not. Now it finds it (I was temporaly using LD_LIBRARY_PATH). Actually, I had never used ldconfig with any other library.  Should I run it every time I compile?

**Comment by xR3b0rn** [comment]
No. ldconfig just creates symbolic links of recent installed libraries to make them visible to the linker.
