### ISSUE TITLE
Error! Expecting <Version> on valid DBC file

### ISSUE THREAD

**Issue by derkomai** [xR3b0rn/dbcppp#36]
I find the following error when trying to call  dbcppp::Network::fromDBC():
```
1:1 Error! Expecting <Version>
1:1 Error! Unexpected token near here!
```

The  first DBC line is :
`VERSION ""`

But whatever string I type into the "", the error is the same.

**Comment by xR3b0rn** [comment]
What is your files encoding?

**Comment by derkomai** [comment]
UTF-8 Unicode text, with very long lines, with CRLF line terminators

I am not allowed to share the db file, but a file like [this one](https://drive.google.com/file/d/16DlnmagUDmQc9ZQfLW0492mFFIR76JVe/view?usp=sharing) with only the version line yields the same error.

**Comment by xR3b0rn** [comment]
Do you have a BOM at the beginning?

**Comment by xR3b0rn** [comment]
Parsing your example file prints the error:
```
1:11 Error! Expecting <NS_>
1:1 Error! Unexpected token near here
```

**Comment by derkomai** [comment]
I dont' think I have a BOM. `isutf8` returns 0 status. For me, running the binary dbcppp works also, even with the full dbc file. The problem appears when I try to load it  with `dbcppp::Network::fromDBC()`.

**Comment by xR3b0rn** [comment]
Which `fromDBC`  are you using? `fromDBC(const char*)` or `fromDBC(std::istream&)`?

**Comment by derkomai** [comment]
The `ifstream` one.

**Comment by derkomai** [comment]
Could you point me to where the implementation of that function is? I can't seem to find it while debugging.

**Comment by xR3b0rn** [comment]
At the end of DBCAST2Network.

**Comment by xR3b0rn** [comment]
Let me know if you could fix it.

If you have not fixed it yet, you can git pull and try again.

**Comment by derkomai** [comment]
I could not try to debug it again yesterday, on Monday I will pull it and try.

**Comment by derkomai** [comment]
It works now. After pulling, I was getting the same error, so I started debugging and found out that the `std::string` that is created from `std::istreambuf_iterator<char>(is)` inside `loadDBCFromIs` was empty... because I'm an idiot and the `ifstream` file was being initialized to a non-existing file due to a file rename. I thought `ifstream` checked for that. Anyway, it works now, thank you!

**Comment by xR3b0rn** [comment]
The `load*FromIs`-functions taking an `std::istream`-reference, which is not necessarily bind to a file, in which it is not possible to check stuff which is related to the underlying file object anymore.

The `loadNetworkFromFile`-function is missing this check. I will add this, thanks for reporting this.
