### ISSUE TITLE
Minimum Boost version

### ISSUE THREAD

**Issue by jackm** [xR3b0rn/dbcppp#37]
Is Boost version 1.72.0 truly the minimum version required? Is so, what is the reason for this version requirement?

I have Boost 1.71.0 installed and I was able to successfully compile, but I wanted to know the reason for choosing version 1.72.0 in CMakeLists.txt

**Comment by xR3b0rn** [comment]
The projects travis file is using boost 1.72.0. I made no further investigations in this direction, but if I remeber correctly, I had problems when building with older versions. Boost is not backward compatible, so you have to try it.

**Comment by ByunghunLee** [comment]
1.69.0 works.

**Comment by OCILY** [comment]
My boost version is 1.65.1, and failed to compile.

**Comment by ByunghunLee** [comment]
> My boost version is 1.65.1, and failed to compile.

Could you give me some information like compiler and os?
Is it failed to build project or compile? can you share the error messages?

**Comment by xR3b0rn** [comment]
The new version of `dbcppp` will come with the required boost headers included. Currently this version of `dbcppp` can be get from the `develop` branch.
