### ISSUE TITLE
"signals" is reserved in Qt

### ISSUE THREAD

**Issue by ozzdemir** [xR3b0rn/dbcppp#41]
I tried to use dbcppp with Qt5, and had `Expected ',' or '...' before 'public' error!` when trying to compile. When I checked it online, I came across to [this thread](https://forum.qt.io/post/86662). When I renamed the signals member value in __Message.h__ and __CAPI.h__ as recommended, I was able to build and use dbcppp. May I recommend renaming it?

**Comment by xR3b0rn** [comment]
Nice to know, thank you!
I will make some checks and the fix it.

**Comment by ozzdemir** [comment]
Forked for the case with minimal changes besides this issue (For adding the library as a 3rdParty to the [PlotJuggler](https://github.com/facontidavide/PlotJuggler/pull/420)). I would like to link to this repository directly, any recommendation?
https://github.com/ozzdemir/dbcppp

**Comment by xR3b0rn** [comment]
I am not sure what you want to do? But you can feel free to create a PR.
