### ISSUE TITLE
Unexpected token in CSS Electronics OBD-II DBC (SG_MUL_VAL_ not supported yet)

### ISSUE THREAD

**Issue by rfrowe** [xR3b0rn/dbcppp#47]
I'm trying to use this library with the [OBD-II DBC](https://github.com/xR3b0rn/dbcppp/files/6193269/CSS-Electronics-OBD2-v1.4.dbc.txt) provided by CSS Electronics. When I try to load this network, I see the following error:
```
221:1 Error! Unexpected token near here!
```

This line is specifically:
```
SG_MUL_VAL_ 2024 S1_PID_00_PIDsSupported_01_20 ParameterID_Service01 0-0;
```

I see `SG_MUL_VAL_` in your grammar and under `NS_` in some test networks. Is extended multiplexing not actually supported?

**Comment by xR3b0rn** [comment]
Thanks for your report. 

To answer your question: No. SG_MUL_VAL_ is currently not supported.

However I am currently working on a handwritten parser to get rid of the boost::spirit dependency. You can observe the progress in the branch v.2.1.0 (Do not use this version in production) .The support of the missing features is on the top most of my TODO list.

**Comment by rfrowe** [comment]
Will the DBC function correctly with those lines removed? I assume it will cripple any associated signals.

**Comment by xR3b0rn** [comment]
`libdbcppp` will be able to parse every line of the message except those two:
```
 SG_ ParameterID_Service01 m1M : 23|8@0+ (1,0) [0|255] "" Vector__XXX
 SG_ ParameterID_Service02 m2M : 23|8@0+ (1,0) [0|255] "" Vector__XXX
```
In case of those two signals `libdbcppp` ignores the `M`. At the moment I am not sure what the `M` means, but if you do not rely on this information, you should be fine.

**Comment by rfrowe** [comment]
It's a bit hard to interpret and I'm not sure myself but I believe those two signals are used as the first of two nested multiplexors

**Comment by xR3b0rn** [comment]
Yeah, you are right, `SG_MUL_VAL_` makes it possible to nest multiplexer signals. So to work with the DBC you need a parser with `SG_MUL_VAL_` support.

**Comment by xR3b0rn** [comment]
I added `SG_MUL_VAL_`-support and pushed it to the branch `feat/v2.1.0`. Let me know if it works.
The exact commit: https://github.com/xR3b0rn/dbcppp/tree/d762bdc5432092c4e6873fc1530ceee7ebb68a3c

**Comment by rfrowe** [comment]
Wow! I'll try it out, thanks. I tried switching to 2.1.0 last week but my CMake got mad. Now it might be worth it to make it work...

**Comment by rfrowe** [comment]
Yes very sad :(
```
Could NOT find Boost (missing: program_options) (found suitable version
    "1.72.0", minimum required is "1.72.0")
```

**Comment by xR3b0rn** [comment]
You have boost 1.72.0 installed? Master builds but feat/2.1.0 does not? And you have boost  1.72.0 installed?

**Comment by rfrowe** [comment]
@xR3b0rn Thanks for the tips. It's a little complicated, since I'm actually using your library in Android. I haven't tried building master, only `v2.0.0` which builds just fine (as it only uses header boost libraries). If you click through to my StackOverflow post, I have pre-compiled `.a` and `.so` libraries for each component. `FindBoost` _is_ looking for `boost_program_options` 
 and it _is_ looking in the right directory but for some reason it can't find `libboost_program_options.so`

**Comment by xR3b0rn** [comment]
I completly removed the boost dependency in the newest commit in `feat/v2.1.0`. Let me know if it works.

**Comment by rfrowe** [comment]
Wow if this works out it will save me a lot of effort :)

* `src/dbcppp/tests/DecodingTest.cpp:14:10: fatal error: '../../include/dbcppp/Network2Functions.h' file not found`
  * Seems like it should be `../include/dbcppp/Network2Functions.h`?
* I have to compile with `-Wno-invalid-constexpr -Wno-c++11-narrowing`
* `src/libdbcppp/DBCParser.h:456:47: error: use of overloaded operator '+' is ambiguous (with operand types 'DBCIterator' and 'int')`
  * Happens numerous other places in `DBCParser.h`

**Comment by xR3b0rn** [comment]
Which compiler do you use?

**Comment by rfrowe** [comment]
Android is using clang++. Here's the full error:
```
  /Users/rrowe/ws/git/auto/x1/seeds/dbc/android/dbc2vss/.cxx/cmake/debug/armeabi-v7a/dbcppp-prefix/src/dbcppp/src/libdbcppp/DBCParser.h:456:47: error: use of overloaded operator '+' is ambiguous (with operand types 'DBCIterator' and 'int')
          if (*in != '\0' && *in == '/' && *(in + 1) == '/')
                                             ~~ ^ ~
  /Users/rrowe/ws/git/auto/x1/seeds/dbc/android/dbc2vss/.cxx/cmake/debug/armeabi-v7a/dbcppp-prefix/src/dbcppp/src/libdbcppp/DBCParser.h:307:17: note: candidate function
      const char* operator+(std::size_t n) const
                  ^
  /Users/rrowe/ws/git/auto/x1/seeds/dbc/android/dbc2vss/.cxx/cmake/debug/armeabi-v7a/dbcppp-prefix/src/dbcppp/src/libdbcppp/DBCParser.h:456:47: note: built-in candidate operator+(const char *, int)
          if (*in != '\0' && *in == '/' && *(in + 1) == '/')
                                                ^
  /Users/rrowe/ws/git/auto/x1/seeds/dbc/android/dbc2vss/.cxx/cmake/debug/armeabi-v7a/dbcppp-prefix/src/dbcppp/src/libdbcppp/DBCParser.h:456:47: note: built-in candidate operator+(const volatile char *, int)
````

**Comment by xR3b0rn** [comment]
Then it is most likely a problem caused by a difference in the compiler. I have to further investigate this in order to fix it.

In the meantime you can use g++ if it is possible.

**Comment by xR3b0rn** [comment]
I was not able to reproduce the error. Which clang version do you use?

**Comment by rfrowe** [comment]
It's the version bundled with Android NDK v21.1.6352462. It reports `Android (6317467 based on r365631c1) clang version 9.0.8`

**Comment by xR3b0rn** [comment]
Added `SG_MUL_VAL_` support in #60 .
