### ISSUE TITLE
include errors in master branch

### ISSUE THREAD

**Issue by mf01** [xR3b0rn/dbcppp#49]
I build the current master 73f53ed35fbafcb09abc2ad14d9fc8cad12c6c65 with following  cmake instruction:
```
ExternalProject_Add(
    dbcppp
    PREFIX ${CMAKE_CURRENT_BINARY_DIR}/external-dbcppp
    GIT_REPOSITORY https://github.com/xR3b0rn/dbcppp.git
    GIT_TAG master
    GIT_SUBMODULES
    GIT_SHALLOW 1
    GIT_PROGRESS 1
    TIMEOUT 10
    CMAKE_ARGS -DCMAKE_INSTALL_PREFIX=${CMAKE_CURRENT_BINARY_DIR}/external-dbcppp/install_dir  -DCMAKE_BUILD_TYPE=Release
    BUILD_IN_SOURCE FALSE
    BUILD_ALWAYS TRUE
    INSTALL_DIR ${CMAKE_CURRENT_BINARY_DIR}/external-dbcppp/install_dir
    LOG_DOWNLOAD ON
)
```
I got some include errors in theses files:
DBCParsingCApi.cpp DBCParsingCppApi.cpp DBCWithSingleLineCommentsParsing.cpp Decoding.cpp
There are too much "../"
EDIT:
Same with 
git clone
mkdir build
cd build
cmake ../dbcppp
make -j

**Comment by xR3b0rn** [comment]
This is fixed in develop since bda3eb862f4d5192b8e33bf21dcfa97ef4737b6a
