### ISSUE TITLE
When Bit timing value is empty, parser does not work.

### ISSUE THREAD

**Issue by ByunghunLee** [xR3b0rn/dbcppp#8]
When the bit time is empty, the parser throws the error.
In your example dbc file,  you tested bit timing section with the BS_: 1 : 15, 2.

According to the vector DBC file format document, Bit_timing section can be empty.
If you need it, I can share the document. I think you already have it.

**Comment by xR3b0rn** [comment]
Fixed with https://github.com/xR3b0rn/dbcppp/commit/41c32bd37a819300fff42a7314cc2a624a3024cb .

**Comment by ByunghunLee** [comment]
How long do you sleep a day?
if you feel my question is meas, please ignore it and forgive me.



2020년 3월 3일 (화) 오후 2:10, xR3b0rn <notifications@github.com>님이 작성:

**Comment by xR3b0rn** [comment]
Like a normal person does. 😄😄
