### ISSUE TITLE
libxml/xmlversion.h: No such file or directory

### ISSUE THREAD

**Issue by MichaelBMiner** [xR3b0rn/dbcppp#98]
Hello,

I am attempting to place this code into my application. libxml2/include/tree.h cannot find libxml/xmlversion.h. This is because it is named as libxml/xmlversion.h.in. If I remove the document type of .in I get compilation errors because of the @symbols. If there a nice way to include your application in another?

**Comment by MichaelBMiner** [comment]
> Hello,
> 
> I am attempting to place this code into my application. libxml2/include/tree.h cannot find libxml/xmlversion.h. This is because it is named as libxml/xmlversion.h.in. If I remove the document type of .in I get compilation errors because of the @symbols. If there a nice way to include your application in another?

Or is there an easy way to compile your code as a library for use in my application?

**Comment by xR3b0rn** [comment]
You have to configure the `libxml2` project using `cmake`. I have never done this, but may be this can be done by simple `cd` into the `libxml2` directory inside your project and execute `cmake .`.

> Or is there an easy way to compile your code as a library for use in my application?
That's the intended usage of the library. To do this follow these instructions:
```
git clone --recurse-submodules https://github.com/xR3b0rn/dbcppp.git
cd dbcppp
mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE=Release ..
make -j
make RunTests
make install
ldconfig # on Unix-systems only
```
After that you have to link against the library.

**Comment by MichaelBMiner** [comment]
Do you think your make commands would work on an iMX6 running a custom linux image?

I know that is a reach but I will test it out.

**Comment by MichaelBMiner** [comment]
I am building a yocto project. Building your project in an automated way in yocto is difficult.  My goal is to copy your binaries onto the device build it against my SDK and deployed as part of my image. 

Does c make automatically turn this into a library for me to use?

**Comment by xR3b0rn** [comment]
`cmake` does creates a build for building a `.so`. After building you have to deploy `libdbcppp.so` and `libxml2.so`.

**Comment by MichaelBMiner** [comment]
I am not familiar with cmake. Is there a command to deploy those? I guess I should ask. Are the .so files created? If so deploying them should be as easy as copying them to a directory

**Comment by xR3b0rn** [comment]
`cmake` is not for deploying. `cmake` just a tool for creating builds such as `make`, `nmake` or whatever. With those builds you can build the `libdbcppp.so` and `libxml2.so`.

**Comment by xR3b0rn** [comment]
They are called 'cmake generators' for a list of generates please see: https://cmake.org/cmake/help/latest/manual/cmake-generators.7.html

**Comment by MichaelBMiner** [comment]
Is it possible to do something similar to this?
https://stackoverflow.com/questions/43772887/cmake-creating-a-static-library

Create a static library file from the CMakeLists.txt, on the surface it seems easy but I cannot get it to build anything when I try to add to the cmake files.

**Comment by MichaelBMiner** [comment]
I will let you know this code does compile using the Yocto project and CMake.
