### ISSUE TITLE
GCC Version

### ISSUE THREAD

**Issue by MichaelBMiner** [xR3b0rn/dbcppp#99]
Hello,

Is there a minimum GCC version that needs to be used to build this?

**Comment by xR3b0rn** [comment]
I guess at least `C++11` must be supported, however its just a guess. I never did any investigations into that direction.

**Comment by MichaelBMiner** [comment]
When cmake starts it does
-- The C compiler identification is GNU 9.4.0
-- The CXX compiler identification is GNU 9.4.0
